

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Color;
/**
 *
 * @author HP
 */
public class REGISTER extends javax.swing.JFrame {
int xx, xy;
    /**
     * Creates new form REGISTER
     */
    public REGISTER() {
        initComponents();
    }
    
    
    void bersih(){
        ct_username.setText("username");
        ct_password.setText("password");
        ct_confirmpassword.setText("confirm password");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new Componen.RoundedPanel();
        j_exit = new javax.swing.JLabel();
        j_desain = new javax.swing.JLabel();
        panel_Transparan1 = new Componen.Panel_Transparan();
        jLabel3 = new javax.swing.JLabel();
        ct_username = new Componen.customTextField();
        jLabel2 = new javax.swing.JLabel();
        ct_password = new Componen.customTextField();
        jLabel1 = new javax.swing.JLabel();
        ct_confirmpassword = new Componen.customTextField();
        b_SIGNUP = new Componen.CustomButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                roundedPanel1MouseDragged(evt);
            }
        });
        roundedPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                roundedPanel1MousePressed(evt);
            }
        });
        roundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/11zon_resized (7).png"))); // NOI18N
        j_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_exitMouseClicked(evt);
            }
        });
        roundedPanel1.add(j_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 45, -1));

        j_desain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/baju.png"))); // NOI18N
        j_desain.setText("jLabel1");
        roundedPanel1.add(j_desain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 146, -1));

        panel_Transparan1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/man.png"))); // NOI18N
        panel_Transparan1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        ct_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        ct_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ct_username.setText("username");
        ct_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ct_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ct_usernameFocusLost(evt);
            }
        });
        panel_Transparan1.add(ct_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/11zon_resized (8).png"))); // NOI18N
        panel_Transparan1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        ct_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        ct_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ct_password.setText("password");
        ct_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ct_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ct_passwordFocusLost(evt);
            }
        });
        panel_Transparan1.add(ct_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 210, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/11zon_resized (12).png"))); // NOI18N
        panel_Transparan1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        ct_confirmpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        ct_confirmpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ct_confirmpassword.setText("confirm password");
        ct_confirmpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ct_confirmpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ct_confirmpasswordFocusLost(evt);
            }
        });
        panel_Transparan1.add(ct_confirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 210, 40));

        b_SIGNUP.setBackground(new java.awt.Color(255, 102, 102));
        b_SIGNUP.setText("SIGN UP");
        b_SIGNUP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_SIGNUPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_SIGNUPMouseExited(evt);
            }
        });
        panel_Transparan1.add(b_SIGNUP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, 30));

        roundedPanel1.add(panel_Transparan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 230, 240));

        jLabel4.setText("YULANDHA STORE");
        roundedPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 130, 40));

        getContentPane().add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 510, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void roundedPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel1MousePressed
         xx = evt.getX();
         xy = evt.getY();
    }//GEN-LAST:event_roundedPanel1MousePressed

    private void roundedPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel1MouseDragged
      int x = evt.getXOnScreen();
      int y = evt.getYOnScreen();
      this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_roundedPanel1MouseDragged

    private void j_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_exitMouseClicked
        dispose();
    }//GEN-LAST:event_j_exitMouseClicked

    private void ct_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ct_usernameFocusGained
        String username=ct_username.getText();
        if(username.equals("username")){
            ct_username.setText("");
        }
    }//GEN-LAST:event_ct_usernameFocusGained

    private void ct_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ct_passwordFocusGained
        String pass=ct_password.getText();
        if(pass.equals("password")){
            ct_password.setText("");
        }
    }//GEN-LAST:event_ct_passwordFocusGained

    private void ct_confirmpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ct_confirmpasswordFocusGained
         String confirmpass = ct_confirmpassword.getText();
         if(confirmpass.equals("confirm password")){
             ct_confirmpassword.setText("");
        }
    }//GEN-LAST:event_ct_confirmpasswordFocusGained

    private void ct_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ct_usernameFocusLost
       String username=ct_username.getText();
       if(username.equals("")||username.equals("username")){
           ct_username.setText("username");
       }
    }//GEN-LAST:event_ct_usernameFocusLost

    private void ct_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ct_passwordFocusLost
        String pass=ct_password.getText();
       if(pass.equals("")||pass.equals("password")){
           ct_password.setText("password");
       }
    }//GEN-LAST:event_ct_passwordFocusLost

    private void ct_confirmpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ct_confirmpasswordFocusLost
       String confirmpass=ct_confirmpassword.getText();
       if(confirmpass.equals("")||confirmpass.equals("confirm password")){
           ct_confirmpassword.setText("confirm password");
       }
    }//GEN-LAST:event_ct_confirmpasswordFocusLost

    private void b_SIGNUPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_SIGNUPMouseEntered
        b_SIGNUP.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_b_SIGNUPMouseEntered

    private void b_SIGNUPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_SIGNUPMouseExited
       b_SIGNUP.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_b_SIGNUPMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new REGISTER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Componen.CustomButton b_SIGNUP;
    private Componen.customTextField ct_confirmpassword;
    private Componen.customTextField ct_password;
    private Componen.customTextField ct_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel j_desain;
    private javax.swing.JLabel j_exit;
    private Componen.Panel_Transparan panel_Transparan1;
    private Componen.RoundedPanel roundedPanel1;
    // End of variables declaration//GEN-END:variables
}
